module.exports = {
  name:      'Abhyaas The Global School',
  shortName: 'Abhyaas',
  tagline:   'Sramayeva Jayathe',
  taglineMeaning: 'Work alone leads to victory',
  established: 2010,
  board:     'CBSE',
  grades:    'Nursery to Class X',
  address:   'Bhimavaram, West Godavari, Andhra Pradesh',
  phone:     '',
  whatsapp:  '',
  email:     'office@abhyaastheglobalschool.com',
  domain:    'abhyaastheglobalschool.com',
  affiliation: '',
  schoolCode:  '',
  principal: {
    name:  '',
    photo: '/images/principal.jpg',
    message: '',
  },
  social: {
    facebook:  '',
    instagram: '',
    youtube:   '',
    twitter:   '',
  },
  vision:  'To nurture globally competent, values-driven individuals through excellence in education.',
  mission: 'Providing a holistic CBSE education that blends academic rigour with character, creativity, and compassion.',
};
